checks:
  similar_code:
    exclude_paths:
      - "contracts/tests/"
  complexity:
    exclude_paths:
      - "contracts/tests/"
engines:
  tslint:
    enabled: true
    checks:
      quotemark:
        enabled: false
exclude_paths:
  - "web/src/graphql/generated.ts"
  - "contracts/deployments/"
  - "contracts/config/"
  - "kleros-sdk/config/"
